# AI Model Configuration and Service Definitions
# Internal configuration file - not intended for user modification

providers:
  google:
    class_path: 'multi_env_sdk.run.ai.gemini_client.GeminiClient'
    description: 'Google Cloud AI models'
    enabled: true
    priority: 1
    models:
      gemini-2.5-pro:
        name: 'Gemini 2.5 Pro'
        description: 'More powerful model for higher quality analysis'
        max_tokens: 8192
        cost_per_1k_tokens: 0.0025
      gemini-2.5-flash:
        name: 'Gemini 2.5 Flash'
        description: 'Fast and cost-effective model for quick analysis'
        max_tokens: 4096
        cost_per_1k_tokens: 0.0015
      gemini-2.5-flash-lite:
        name: 'Gemini 2.5 Flash Lite'
        description: 'Ultra-fast lightweight version of 2.5 Flash'
        max_tokens: 2048
        cost_per_1k_tokens: 0.001


